env:
  global:
    - CC_TEST_REPORTER_ID=430594ee361ff2e93ebf0a942f639b8092c6f17b7c5098f9c75abc404311dfc7
language: java
dist: xenial
jdk:
- openjdk8
- openjdk9
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./gradlew clean build jacocoTestReport
after_script:
  - JACOCO_SOURCE_PATH=src ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
notifications:
  slack:
    secure: DIAJW9rKJA8Btxe2gxRh39d2/AHKTeJeJIV5fr7dnh2SqRTcoXQU0fMFVjS09VEoReKmGYyoLsh5LCAdD+2eLc16RtWk4dEEz7SelZMzCmB2jdaTFyK5QlDU6cfQZW6FW23UZWKRQisHq77++NWrdPL97rFcWzNqiuefWOdVIWwiy32xw/4EaqgrgzCPQFBP9fgWnNBdN7FnD23SlBhVgNnWL2wUmOFQo3J/OnbYK54gK4woeIKfMuPclSI0HHu366GMtBr9DeuDtWrTzPJ4xavnRIK2jndxEoNYJNs0/ta2z3IrLmRDNzyzjjRCIj37xQlmFFEvvfgsTJzSkg5ZhAK/v2wJ1ZO2eChgh5YLALMK/dSkExuSCPmHrpchsm2gQe61lXOsoFvf8ZXBNQ1t6yAnyYeVlIEnvIderb03cWOcxOMGu3QS6HR7SbiB8JMaoV9x3L2R9rIsf8QFGogbn7gliDUueaOlWfX24ChZGs8kQK+INDWLpbBkNLPwA5H4S61UWeP1VZ6mlHwfd3SQ3EcWDZgQ5+nyD7XVq6QySBDwqkD9nUA7SBuGEtaym5YoyIaVmz36XXd87IJKXQSZTZTeLol7YJ/BVFRkDeMHlxkPeQurE7wx0W//taOsn5Nafb90fUj4A+q22RwoifbXAv1j2y7iBRaGjb2mkMNZ8cM=
