#! /bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
HOSTIP=`ip -4 addr | grep global | awk '{print $2}' | cut -d / -f 1 | sed -n 1p`
docker run -it --name jdk --rm \
-d \
-h jdk \
-w /ros \
-v ${SCRIPTPATH}/:/ros/ \
--net=gm_network \
-e DISPLAY=$DISPLAY \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v "$HOME/.Xauthority:/root/.Xauthority:rw" \
--privileged \
--add-host $HOSTNAME:$HOSTIP \
rgudwin/jdk8_x11:1.0

# The following dependencies should be installed for X to work:
# apt install libxext6 libxrender1 libxtst6 libxi6

