/*
 * /*******************************************************************************
 *  * Copyright (c) 2012  DCA-FEEC-UNICAMP
 *  * All rights reserved. This program and the accompanying materials
 *  * are made available under the terms of the GNU Lesser Public License v3
 *  * which accompanies this distribution, and is available at
 *  * http://www.gnu.org/licenses/lgpl.html
 *  * 
 *  * Contributors:
 *  *     K. Raizer, A. L. O. Paraense, R. R. Gudwin - initial API and implementation
 *  ******************************************************************************/
 
package br.unicamp.cst.attention;

import br.unicamp.cst.core.entities.Codelet;
import br.unicamp.cst.core.entities.MemoryObject;
import br.unicamp.cst.support.TimeStamp;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 * Codelet implementation of a Combined Feature Map (CFM). The CFM is a signal 
 * composed of all feature maps generated (bottom-up and top-down), obtained 
 * through the sum of the products between an element of the feature weight 
 * vector in the attentional system (w_{f_{j_t}}) and a given feature map (F_{i_{j_t}}). 
 * 
 * The type of the winning characteristic of the bottom-up or top-down cycle is 
 * classified before the application of the feedback inhibition algorithm. 
 * 
 * Two values​are obtained during the formation of the Combined Feature Map: 
 * (i) the sum of the values​generated by the bottom-up feature maps and 
 * (ii) the sum of the values ​​generated by the top-down feature maps. 
 * 
 * If (i) > (ii), the winner of the attentional cycle is classified as bottom-up. 
 * If (ii) > (i), the winner of the attentional cycle is classified as top-down.
 * 
 * @author leolellisr
 * 
 * @see Codelet
 * @see MemoryObject
 * @see FeatMapCodelet
 * @see CombFeatMapCodelet
 */
public class CFM extends CombFeatMapCodelet {
    private static final int BOTTOM_UP = 0;
    private static final int TOP_DOWN = 1;
    private  int time_graph;
    public int steps;
    private boolean print_to_file = false, debug;
    private List CFMrow, winners_row;
    
    /**
     * init CFM class
     * @param numfeatmaps
     *          input feature maps number
     * @param featmapsnames
     *          input feature maps names
     * @param timeWin
     *          analysed time window,   Buffer size
     * @param CFMdim 
     *          output combined feature map dimension
     * @param print_to_file
     *          boolean that defines if should print to file
     * @param debug
     *          boolean that defines if should print debug logs
     */
    public CFM(int numfeatmaps, CopyOnWriteArrayList<String> featmapsnames, int timeWin, int CFMdim, boolean print_to_file, boolean debug) {
        super(numfeatmaps, featmapsnames,timeWin,CFMdim);
        this.time_graph = 0;
        this.print_to_file = print_to_file;
        this.steps = 0;
        this.debug = debug;
    }

     /**
     * init CFMrow and WinnersRow. Initializes lists to receive new values of
     * CFM and Winners.
     */
    private void initializeCFMrowAndWinnersRow() {
    for (int j = 0; j < CFMdimension; j++) {
        this.CFMrow.add((float) 0);
        this.winners_row.add(0);
        }
    }
    
    /**
     * Calculate CFM and winners type. Calculates the CFM through the sum of the 
     * products between an element of the feature weight vector in the 
     * attentional system and a given feature map, and defines the type of the 
     * winning characteristic (bottom-up or top-down)
     */
    private void calculateCFMandWinners() {
        List weight_values = (List) weights.getI();
        for (int j = 0; j < CFMrow.size(); j++) { 
                float ctj= 0, sum_top=0, sum_bottom=0;
                for (int k = 0; k < num_feat_maps; k++) { 
                    MemoryObject FMkMO = (MemoryObject) feature_maps.get(k);
                    List FMk = (List) FMkMO.getI();
                    if(FMk == null || weight_values == null) return;
                    if(FMk.size() < 1) return;
                    List FMk_t = (List) FMk.get(FMk.size()-1);
                    Float fmkt_val = (Float) FMk_t.get(j), weight_val = (Float) weight_values.get(k);
                    ctj += weight_val*fmkt_val;
                    if(k>=4) sum_top += weight_val*fmkt_val;
                    else sum_bottom += weight_val*fmkt_val; 
                }   
                CFMrow.set(j, ctj);
                if(sum_top > sum_bottom) winners_row.set(j, TOP_DOWN);
                else winners_row.set(j, BOTTOM_UP); 
            }
    }
    
    /**
     * Reset triggers.
     */
    public void resetTriggers() {
        steps = 0;
    }
    
    /**
     * Main class of CFM. Executed every proc. Initializes the new arrays for 
     * CFM and winners
     */
    @Override
    public void calculateCombFeatMap() {
        try {
            Thread.sleep(300);
        } catch (Exception e) {
            Thread.currentThread().interrupt();
        }
        List combinedFM = (List) comb_feature_mapMO.getI(), winnersTypeList = (List) winnersType.getI();
        if(combinedFM.size() == timeWindow) combinedFM.remove(0);
        if(winnersTypeList.size() == timeWindow) winnersTypeList.remove(0);
        combinedFM.add(new CopyOnWriteArrayList<>());
        winnersTypeList.add(new CopyOnWriteArrayList<>());
        CFMrow = (List) combinedFM.get(combinedFM.size()-1);
        winners_row = (List) winnersTypeList.get(winnersTypeList.size()-1);
        
        initializeCFMrowAndWinnersRow();
        
        calculateCFMandWinners();
        if(debug){
            Logger.getAnonymousLogger().log(Level.INFO, "I received {0} maps as inputs", num_feat_maps);
            for (int i = 0; i < num_feat_maps; i++) {
                MemoryObject inp = (MemoryObject)feature_maps.get(i);
                Logger.getAnonymousLogger().log(Level.INFO, "{0} {1} : steps: {2} Timestamp after: {3}",  new Object[]{i, feat_maps_names.get(i), this.steps, TimeStamp.getStringTimeStamp(inp.getTimestamp(),"dd/MM/yyyy HH:mm:ss.SSS")});
            }
        }
        comb_feature_mapMO.setI(CFMrow);
        
        if(debug) Logger.getAnonymousLogger().log(Level.INFO, "CFM: steps: {0} Timestamp after: {1}",  new Object[]{this.steps, TimeStamp.getStringTimeStamp(comb_feature_mapMO.getTimestamp(),"dd/MM/yyyy HH:mm:ss.SSS")}); 
            
        if(print_to_file){
            printToFile((CopyOnWriteArrayList<Float>) CFMrow, "CFM.txt");
            printToFile((CopyOnWriteArrayList<Integer>) winners_row, "winnerType.txt"); 
        }
        steps++;
    }
    
      
    private void printToFile(Object object,String filename){
        String user_dir = System.getProperty("user.dir");
        File dir = new File(user_dir);
        if (!dir.exists()) {
            dir.mkdir();
            if(debug) Logger.getAnonymousLogger().log(Level.INFO, "dir created: {0}",  new Object[]{dir});

        }
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy_MM_dd_HH_mm_ss");  
        LocalDateTime now = LocalDateTime.now();
            try(FileWriter fw = new FileWriter(user_dir+filename,true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter out = new PrintWriter(bw))
            {
                out.println(dtf.format(now)+"_"+"_"+time_graph+" "+ object);
                time_graph++;
                out.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
    
    }
}